# Managed by demo/lib.sh
DJANGO_EMAIL_URL_APP={{DOCS_FRONTEND_URL}}
DJANGO_EMAIL_LOGO_IMG={{DOCS_FRONTEND_URL}}/assets/logo-suite-numerique.png
IMPRESS_BASE_URL={{DOCS_BACKEND_URL}}
MEDIA_BASE_URL={{DOCS_MEDIA_URL}}

OIDC_OP_JWKS_ENDPOINT={{KEYCLOAK_INTERNAL_URL}}/realms/{{KEYCLOAK_REALM}}/protocol/openid-connect/certs
OIDC_OP_AUTHORIZATION_ENDPOINT={{OIDC_ISSUER}}/protocol/openid-connect/auth
OIDC_OP_TOKEN_ENDPOINT={{KEYCLOAK_INTERNAL_URL}}/realms/{{KEYCLOAK_REALM}}/protocol/openid-connect/token
OIDC_OP_USER_ENDPOINT={{KEYCLOAK_INTERNAL_URL}}/realms/{{KEYCLOAK_REALM}}/protocol/openid-connect/userinfo
OIDC_OP_INTROSPECTION_ENDPOINT={{KEYCLOAK_INTERNAL_URL}}/realms/{{KEYCLOAK_REALM}}/protocol/openid-connect/token/introspect
OIDC_OP_URL={{OIDC_ISSUER}}

OIDC_RP_CLIENT_ID={{DOCS_OIDC_CLIENT_ID}}
OIDC_RP_CLIENT_SECRET={{DOCS_OIDC_CLIENT_SECRET}}
OIDC_RP_SIGN_ALGO=RS256
OIDC_RP_SCOPES=openid email
OIDC_AUTH_REQUEST_EXTRA_PARAMS={}
OIDC_REDIRECT_ALLOWED_HOSTS=localhost:{{LASUITE_AUTH_PORT}},localhost:{{DOCS_FRONTEND_PORT}}
LOGIN_REDIRECT_URL={{DOCS_FRONTEND_URL}}
LOGIN_REDIRECT_URL_FAILURE={{DOCS_FRONTEND_URL}}
LOGOUT_REDIRECT_URL={{DOCS_FRONTEND_URL}}

OIDC_RESOURCE_SERVER_ENABLED=True
OIDC_RS_CLIENT_ID={{DOCS_OIDC_CLIENT_ID}}
OIDC_RS_CLIENT_SECRET={{DOCS_OIDC_CLIENT_SECRET}}
OIDC_RS_AUDIENCE_CLAIM=client_id
OIDC_RS_ALLOWED_AUDIENCES={{DOCS_OIDC_ALLOWED_AUDIENCE}}

USER_RECONCILIATION_FORM_URL={{DOCS_FRONTEND_URL}}
COLLABORATION_SERVER_ORIGIN={{DOCS_FRONTEND_URL}}
COLLABORATION_WS_URL={{DOCS_COLLABORATION_WS_URL}}
COLLABORATION_WS_NOT_CONNECTED_READ_ONLY=False
